ALTER TABLE IF EXISTS property ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN DEFAULT TRUE;
UPDATE property SET auto_renew = TRUE WHERE auto_renew IS NULL;
ALTER TABLE IF EXISTS property ALTER COLUMN auto_renew SET DEFAULT TRUE;
